### ISSUE TITLE
Sequences vs arrays

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/api-design-guide#1] opened 2013-08-28 15:32 UTC
It would be great if the document could provide guidance on when to use a sequence vs when to use an array in an API. 

See:
https://github.com/sysapps/telephony/issues/81

**Comment by torgo** [comment] 2017-09-28 12:13
This repo is a duplicate of w3ctag/design-principles . So we are closing this here.

**Closed by torgo** 2017-09-28 12:13 UTC
Labels: enhancement
